services:
  mysql8:
    # 指定容器的名称
    container_name: mysql_8   
    # 指定镜像和版本
    image: mysql:8.0           
    platform : ${PLATFORM}
    ports:
      - "${MYSQL_PORT}:3306"
    restart: always
    # 容器日志大小配置
    logging:
      driver: 'json-file'
      options:
        max-size: '5g'
    volumes:
      # 挂载数据目录,当前文件使用./mysql/data
      - ${DOCKER_DATA_PATH}/mysql/mysql8/data:/var/lib/mysql
      # 挂载配置文件目录
      - ${DOCKER_DATA_PATH}/mysql/mysql8/config:/etc/mysql/conf.d
      # 挂载其他中间文件,例如SQL
      - ${DOCKER_DATA_PATH}/mysql/mysql8/opt:/opt
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_USER: 'user'
      MYSQL_PASS: '123456'
    networks:  # 网络配置
      - docker-dev-network  # 加入到 docker-dev-network 网络

networks:  # 网络
  docker-dev-network:
      # 如果不存在,就注释external: true,那么会创建先该网络
      # 否则提示:network docker-dev-network declared as external, but could not be found
      external: true # 表示网络已存在,无需再次创建.