services:
  cm_db:
    image: mysql:5.7.31
    volumes:
      - /Users/dongfeng/docker_data/chainmaker/db_data:/var/lib/mysql
    # restart: always
    privileged: true 
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Baec&chainmaker
      MYSQL_USER: chainmaker
      MYSQL_PASSWORD: Baec&chainmaker
      MYSQL_DATABASE: chainmaker_dev
    command: [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_general_ci',
        '--max_connections=3000']
    networks:  # 网络配置
      - docker-dev-network  # 加入到 docker-dev-network 网络

  cm_mgmt_server:
    depends_on:
      - cm_db
    image: chainmakerofficial/management-backend:v2.3.5
    ports:
      - "9999:9999"
    # restart: always
    networks:  # 网络配置
      - docker-dev-network  # 加入到 docker-dev-network 网络

  cm_mgmt_web:
    depends_on:
      - cm_mgmt_server
    image: chainmakerofficial/management-web:v2.3.5
    ports:
      - "80:80"
    # restart: always
    networks:  # 网络配置
      - docker-dev-network  # 加入到 docker-dev-network 网络

networks:  # 网络
  docker-dev-network:
      # 如果不存在,就注释external: true,那么会创建先该网络
      # 否则提示:network docker-dev-network declared as external, but could not be found
      external: true # 表示网络已存在,无需再次创建.