---
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password
    volumes:
      - /opt/daocker_data/wordpress/mysql_data:/var/lib/mysql
    networks:  # 网络配置
      - docker-dev-network  # 加入到 docker-dev-network 网络
  wordpress:
    image: wordpress:latest
    depends_on:
      - mysql
    ports:
      - 8080:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password
    volumes:
      - /opt/daocker_data/wordpress/wordpress/wp-content:/var/www/html/wp-content
    networks:  # 网络配置
      - docker-dev-network  # 加入到 docker-dev-network 网络
volumes:
  mysql_data:



networks:  # 网络
  docker-dev-network:
      # 如果不存在,就注释external: true,那么会创建先该网络
      # 否则提示:network docker-dev-network declared as external, but could not be found
      external: true # 表示网络已存在,无需再次创建.